// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example usage:
///
/// ```dart
/// import 'firebase_options.dart';
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL4AWoS9Wh3nDRt2jMHwlK1KmOUQD-P78',
    appId: '1:769834710113:web:5d02a9b8625634d079e620',
    messagingSenderId: '769834710113',
    projectId: 'new-app-58549',
    authDomain: 'new-app-58549.firebaseapp.com',
    storageBucket: 'new-app-58549.firebasestorage.app',
    measurementId: 'G-PKQ9XSDYGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbhPKjUD_587rRcPNm30j-KjE0xJTt8Jw',
    appId: '1:769834710113:android:0b03e7917e2d6e4d79e620',
    messagingSenderId: '769834710113',
    projectId: 'new-app-58549',
    storageBucket: 'new-app-58549.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp19XJp2x0NhjiDrfxUilNMahDWrP5Jds',
    appId: '1:769834710113:ios:5074d4916b8a08c379e620',
    messagingSenderId: '769834710113',
    projectId: 'new-app-58549',
    storageBucket: 'new-app-58549.firebasestorage.app',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp19XJp2x0NhjiDrfxUilNMahDWrP5Jds',
    appId: '1:769834710113:ios:5074d4916b8a08c379e620',
    messagingSenderId: '769834710113',
    projectId: 'new-app-58549',
    storageBucket: 'new-app-58549.firebasestorage.app',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL4AWoS9Wh3nDRt2jMHwlK1KmOUQD-P78',
    appId: '1:769834710113:web:d2fd03d9e2ab708679e620',
    messagingSenderId: '769834710113',
    projectId: 'new-app-58549',
    authDomain: 'new-app-58549.firebaseapp.com',
    storageBucket: 'new-app-58549.firebasestorage.app',
    measurementId: 'G-LMQTL0K7GJ',
  );
}
